github:
  username: octocat

github_auth_token: ~
anthropic_api_key: ~

sunetid: testuser
name: Test User

control_master_host: sdr-infra
vpn_host: su-vpn.stanford.edu

repository_source: https://raw.githubusercontent.com/sul-dlss/sdr-deploy/main/config/settings.yml
update_branch: update-dependencies

honeybadger_api:
  url: https://app.honeybadger.io/v2
  max_faults: 10
  max_deploys: 10
